### PR TITLE
rocal updates 

### PR DESCRIPTION
**Pull request by LakshmiKumar23**
- api changes to match rocal
- training updates to match new API
- name changes to rocal
- python3 updates

### CODE REVIEW

**Comment by LakshmiKumar23** [comment]
@hansely Can you test this on your system when you get a chance? I am not able to run Qt
@kiritigowda will need to make sure Hansel can run this

**Comment by hansely** [comment]
@LakshmiKumar23 @kiritigowda 
It looks like the qt apis need to be updated to support pyqt5.
I can look into this later.

**Review by kiritigowda — APPROVED** [review]

**Comment by kiritigowda** [comment]
@hansely can you test this PR?

**Comment by hansely** [comment]
> @hansely can you test this PR?

the PR is not ready yet according to Lakshmi. Will test it when it is ready

**Comment by LakshmiKumar23** [comment]
@hansely Inference part ready to test. Needs some Qt changes that you have to look into. Training part is in progress

**Comment by LakshmiKumar23** [comment]
> @hansely Inference part ready to test. Needs some Qt changes that you have to look into. Training part is in progress

Updated training scripts as well

**Comment by LakshmiKumar23** [comment]
> > @hansely Inference part ready to test. Needs some Qt changes that you have to look into. Training part is in progress
> 
> Updated training scripts as well. Both inference and training works now. @hansely let me know if you want to fix qt bugs on this PR itself or a new one

**Comment by LakshmiKumar23** [comment]
@kiritigowda This PR can be merged

**Pull request merged**
